spring:
  datasource:
    url: jdbc:mysql://localhost:3306/scott
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: scott
    password: tiger



server:
  port: 8100


spring-boot:
  run:
    jvmArguments: -parameters